[[GMP]]
arch = "aarch64"
git-tree-sha1 = "8d0d8f241aa20d8c3874d5bd523b55c9148b0820"
os = "macos"

    [[GMP.download]]
    sha256 = "b6da91236bf90bccd7b14663bc6c6cf6e09aaffb577559cb1493fb02a07a9600"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bb260496f5bdc20241149378b1bb402186b41ff"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "d42d2a78a1b1c95f10d3b2512d3a2e275e4c7028a873093868da8ecbac2da682"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45edf6327575efbbce9b4a455cbb57c155effb0f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a6a159f3f4f6e1e79c6af19ab446257f798efd066c5b2ab3ea2c8db68a0f18bc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab67845a7c19ffb874965e18e25c3d5fe609b006"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "07607c305c11e163e8d2db00707bfaafeb58f213b866ff6aea4e36c40cc850f2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bff6dbadf401034c7eb0285d543e36b8f173707e"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "5f6aa3b217ba82e1f9fa73a96b06d07fe64159068bd17093d87a5c1a5571a26d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10dff2cd5267d559a8696b5b271b5549edde1e97"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "34c96d81a6680a4459e37a22c09e2f9667b3982fd323e44250dde50275799e28"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "091e4225bc364e86ff37bc088ef56c745afb2510"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "eee16a11eb3a53951fc8ffbf69b5115f4ee981761a0b6426a23773ff6ed763b0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9da2753b70301afcbfb51d1d95e492e773662877"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "36161cb38015546ad21b43f6f350c0218b23c066f067d202c4a6fee9369c0f36"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cbf05ec2c2243a753ed665d431122611fe2b18b"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "45397d33ada80b364e06f171be1c0aa0fc57aaf15230591a4cee522507a9206d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ca603211b43fa3fb979f2a7890b2806e03249ce"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "3c9c353f4953bdc853eb2743ea9c8f629a658b1dc072962858857c05571de9e9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "732d458037a8589b0e6497a0621fd4e00a33c9b5"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "e949f0f2dfa2a5a9881e6f4d81d4ba509098966c48a525a78904749023d4f3b1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18dc781fce0a29c37336bde7c9bd2a35cb2ccdc8"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "23948309e929b71b0de806ae1266a43abc904abb6cdc4a03c2677c474512aa88"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffdb5b251a4b6f775c432bd4b462a7bfed67f116"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "54584a11df4f048b429bd05be456ea44cfce3d2942cd3ae9fca0b9d7347628c9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b3f3220e8cf52bb6df5af251717cbc466e40805"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "188e805c53f654e0cd7017f744556323549fff905890ed1cfa470f20570cee8c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d67430db41a41201d0d27105c067ad91f606818"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "0730238c033f2c0fc6a5251c92165df0c24f4455cfae33cff471b4cef1cc5610"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1785045bb73369e850772293b3aa5b435d598b48"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9510a85c2dd35454e7e0b37cd6bf35c69b73187f6df6ac69aa7dd50c5d395398"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "691758e68edce5e8242c73c556094d5ba4032463"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "1d4175563f725268aab2504013adbd6017af82b9d09a2e532e2bf9fcd1685013"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "711d4ad03f0f8b735fe965d91d8d732e8effab65"
os = "windows"

    [[GMP.download]]
    sha256 = "80f13a692df5ce0ea5f9ff9bfcb5dca81816df98e3bc6f129aac9e3792448983"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38fe70480820684f1d0f53a2661ac15199bf33fb"
os = "windows"

    [[GMP.download]]
    sha256 = "a941e7dd990f5c493cf0cf601715e479a304415dfec6fa675487f3e9cc1ed9e1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0045f143390793bb108eee3e157a695e70d3817"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ae58c9b17fbceb459607f4bd3d19a2292ff7dd60541d9cbb58187bef78203975"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c490836adf419b7c0a04db6ce0002c351ebe0075"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c47825e55c671de055c0e61d289d463230834edfc3920a67ef62eb4b8527e058"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "76633a301a266cd900bd12ad31da4d924f82b188"
os = "macos"

    [[GMP.download]]
    sha256 = "bc66d1afc0ab8827cac2203055420a87314969deb2cf48ea9fa86b000053738c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "603c2ffc8c74dded23b8621a24358994d00a7401"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a6fa13fe208c2eaff9d36bf9d0ac301f9a92ac4b737f5c5a7bbd33d7077996e3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c207c7dc70b23755d9281a92daa9b8f11dc746d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "cb20b68a814c37fa091f38a83f160c5025ecf3234401758c9ca820b10adc58b0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39f2114e977d935092e5a4cb4c57e93862ba58bf"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "f5524497ac4b8eba03c0b4c26c957fbdc601d236afd1ce502e44cadc77e56e63"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-linux-gnu-cxx11-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f62a19b53f4b1b5152d2cfa390d0941afb064973"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9d0227a041d02dc5907d048fb8f16314a8a17eb2a6ef1e086a3d312d78efbc83"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "620643787a840bb90ef58d4b00e5af0b196be188"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "c6b5537a888b1fdd0d2890b3184a4524c5cd3fbdd8d92cc497be413846fc0c7c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "d83fab5cd0e65d42ef43a5f1f01d999646a9e7b1"
os = "freebsd"

    [[GMP.download]]
    sha256 = "8782c91a1f22585169c7d5cba7d976066afe464fad75c6d5a6161bf198afe43d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcbed3fe7f2be4e3528cb586a6bc4f5ba6457258"
os = "windows"

    [[GMP.download]]
    sha256 = "9547ad1205a106a1d94c710eb088c12e498721295c6d4195def74b78116c05b2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbfb55cb698b0d08729d524cdb83ffbaf0bb844c"
os = "windows"

    [[GMP.download]]
    sha256 = "0896c70713734933fb552d2783cff8771706d7c2f4e188e00fd93f918f09b2f8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+6/GMP.v6.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
