name = "ChunkCodecLibBrotli"
uuid = "653b0ff7-85b5-4442-93c1-dcc330d3ec7d"
authors = ["nhz2 <nhz2@cornell.edu>"]
version = "0.2.1"

[deps]
ChunkCodecCore = "0b6fb165-00bc-4d37-ab8b-79f91016dbe1"
brotli_jll = "4611771a-a7d2-5e23-8d00-b1becdba1aae"

[compat]
ChunkCodecCore = "0.5"
brotli_jll = "1"
julia = "1.9"

[workspace]
projects = ["test"]
