[general]
library_name = "libzstd"
output_file_path = "../src/LibZstd_clang.jl"
module_name = "LibZstd"
jll_pkg_name = "Zstd_jll"
export_symbol_prefixes = ["ZSTD_", "ZDICT_"]
prologue_file_path  = "./prologue.jl"
use_julia_native_enum_type = true
print_using_CEnum = false
