# Autogenerated wrapper script for DecFP_jll for aarch64-apple-darwin
export libbid

JLLWrappers.@generate_wrapper_header("DecFP")
JLLWrappers.@declare_library_product(libbid, "@rpath/libbid.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbid,
        "lib/libbid.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
